---
title: "right_whale_code"
author: "Tanya Yeung"
date: "2026-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#| label: Load-in-library-and-csv

library(tidyverse)
library(lubridate)

whales <- read.csv("~/Desktop/CSUMB/25-26/Spring 26/Stats 210 /Labs/Right Whales/stats210_portfolio_RW/23305_RWSAS.csv")

```


```{r}
#| label: Cleaning-data 

whales_clean <- whales |> 
  select(-DUPLICATE, -MOM_CALF) |> 
  mutate(sighting = dmy(SIGHTINGDATE),
         certainty = as.factor(CERTAINTY),
         category = as.factor(CATEGORY)) |> 
  select(-SIGHTINGDATE, -CERTAINTY, -CATEGORY) |> 
  drop_na() |> 
   arrange(sighting) |> 
  filter(certainty == "Definite") |> 
  mutate(
    area = case_when(
      LAT > 40 ~ "North",
      LAT > 35 ~ "Mid",
      TRUE ~ "South"
    )
  ) 
  
```

```{r}
#| label: Pivoting-and-summarising-data 

pivot_whale <- whales_clean |> 
  group_by(category) |> 
  summarise(mean_group = mean(GROUPSIZE, na.rm = TRUE),
            count = n())
```

```{r}
#| label: Count-sightings-by-area

desired_order <- c("North", "Mid", "South")
whales_clean$area <- factor(whales_clean$area, levels = desired_order)

area_counts <- whales_clean |> 
  group_by(area) |> 
  summarise(count = n())

ggplot(area_counts, aes(area, count))+
  geom_col()+
  labs(
    title = "Right Whale sighting by area",
    x = "Area",
    y = "Number of sightings"
  )

# This graph shows where right whale sightings are oftenly seen 


```
```{r}
#| label: Graphing-whethe-group-size-vary-across-sighting-types

ggplot(whales_clean, aes(x = reorder(category, -GROUPSIZE), y = GROUPSIZE))+
  geom_boxplot()+
  coord_flip()+
  scale_y_log10()+
  labs(
    title = "Group sizes across sighting types",
    x = "Sighting type",
    y = "Whale group size"
  ) +
  theme_bw()
```

```{r}
#| label: Statistical-Testing

aov_whale <-aov(GROUPSIZE ~ category, data = whales_clean)
summary(aov_whale)

# F(8, 12451) = 32, p < 2e-16, there is a statically significant difference in group size across sighting types (there is at least ONE DIFFERENCE)

TukeyHSD(aov_whale)
```

```{r}
#| label: Mom-and-calf-sighting

mom_baby <- whales |> 
  select(-DUPLICATE, -CATEGORY) |> 
  mutate(
    SIGHTINGDATE = dmy(SIGHTINGDATE),
    month = month(SIGHTINGDATE, label = TRUE),
    season = case_when(
      month %in% c("Mar","Apr","May") ~ "spring",
      month %in% c("Jun", "Jul", "Aug") ~ "summer",
      month %in% c("Sep", "Oct", "Nov") ~ "fall",
      month %in%  c("Dec", "Jan", "Feb") ~ "winter"
  )) |> 
  mutate(
    area = case_when(
      LAT > 40 ~ "North",
      LAT > 35 ~ "Mid",
      TRUE ~ "South"
    )
  )


baby_area_count <- mom_baby |> 
  count(area, season)

  
```

```{r}
#| label: Mom-calf-sighting-graph


desired_order <- c("North", "Mid", "South")
baby_area_count$area <- factor(baby_area_count$area, levels = desired_order)


ggplot(baby_area_count, aes(season, n, fill = area))+
  geom_col(position = "dodge")+
  scale_y_log10()+
  labs(
    title = "Whale mom and calf sighting in different areas",
    x = "Season",
    y = "Number of Sightings"
  )+
  theme_bw()
  
ggplot(baby_area_count, aes(season, n, fill = season))+
  geom_boxplot()+
  scale_y_log10()+
  labs(
    title = "Number of sightings of whale mom and calf",
    x = "Season",
    y = "Number of sightings"
  )+
  theme_bw()

```

```{r}
#| label: relationship-between-calf-and-groupsize

group_baby <- mom_baby |> 
  count(MOM_CALF, GROUPSIZE)

ggplot(mom_baby, aes( ))+
  geom_point()+
  geom_smooth()
```





